### ISSUE TITLE
helm chart fails to run

### ISSUE THREAD

**Issue by bainss** [aescanero/helm-charts#5]
I'm seeing this when I install the helm chart with crash loop back-off

helm install powerdns-release -f values.yaml aecharts/powerdns

using the values file from your repo and just changing the domain

❯ kgl powerdns-release-6c85b7898f-cpwwp powerdns-powerdnsadmin
===> Waiting for 127.0.0.1 MySQL service
Connection to 127.0.0.1 3306 port [tcp/mysql] succeeded!
Using base prefix '/usr'
New python executable in /opt/pdnsadmin/flask/bin/python3
Not overwriting existing python script /opt/pdnsadmin/flask/bin/python (you must use /opt/pdnsadmin/flask/bin/python3)
Installing wheel...done.
===> DB management
---> Running DB Migration
Usage: flask db migrate [OPTIONS]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
Usage: flask db upgrade [OPTIONS] [REVISION]

Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
===> Update PDNS API connection info
Connection problem (1146, "Table 'powerdns.setting' doesn't exist")
Connection problem (1146, "Table 'powerdns.setting' doesn't exist")
[2020-06-19 08:25:17 +0000] [23] [INFO] Starting gunicorn 19.7.1
[2020-06-19 08:25:17 +0000] [23] [INFO] Listening at: http://0.0.0.0:9191 (23)
[2020-06-19 08:25:17 +0000] [23] [INFO] Using worker: sync
[2020-06-19 08:25:17 +0000] [25] [INFO] Booting worker with pid: 25
[2020-06-19 08:25:17 +0000] [25] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'app'

**Comment by aescanero** [comment]
The container was updated, please check again

**Comment by aescanero** [comment]
Chart upgrade to 0.1.7 and tested in EKS

**Comment by bainss** [comment]
Works on bare metal cluster too now @aescanero.

thank you
